# Generated by Django 5.0.1 on 2024-10-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipher', '0003_text_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
