# Generated by Django 5.0.1 on 2024-10-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipher', '0004_text_is_encrypted_text_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='original_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
